name: ee
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=0_gnu
  - affine=2.3.0=py_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py38_0
  - boost-cpp=1.72.0=h8e57a91_0
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.4.5.1=hecc5488_0
  - cachetools=3.1.1=py_0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2020.4.5.1=py38h32f6830_0
  - cffi=1.14.0=py38hd463f26_0
  - cfitsio=3.470=hb60a0a2_2
  - chardet=3.0.4=py38h32f6830_1006
  - click=7.1.1=py_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py38_0
  - cryptography=2.8=py38h766eaa4_2
  - curl=7.67.0=hbc83047_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - earthengine-api=0.1.217=pyh9f0ad1d_0
  - entrypoints=0.3=py38_0
  - expat=2.2.9=he1b5a44_2
  - fiona=1.8.13=py38h900e953_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.1=he06d7ca_0
  - freexl=1.0.5=h14c3975_1002
  - future=0.18.2=py38h32f6830_1
  - gdal=3.0.4=py38h172510d_3
  - geopandas=0.6.1=py_0
  - geos=3.8.1=he1b5a44_0
  - geotiff=1.5.1=hcbe54f9_9
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.2.1=h516909a_2
  - glib=2.58.3=py38h73cb85d_1004
  - google-api-core=1.16.0=py38_1
  - google-api-python-client=1.8.0=pyh8c360ce_0
  - google-auth=1.12.0=pyh9f0ad1d_0
  - google-auth-httplib2=0.0.3=py_3
  - google-cloud-core=1.3.0=py_0
  - google-cloud-storage=1.26.0=py_0
  - google-resumable-media=0.5.0=py_1
  - googleapis-common-protos=1.51.0=py38_1
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - httplib2=0.17.1=pyh9f0ad1d_0
  - icu=64.2=he1b5a44_1
  - idna=2.9=py_1
  - ipykernel=5.1.4=py38h39e3cac_0
  - ipython=7.13.0=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - jedi=0.16.0=py38_1
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - json-c=0.13.1=h14c3975_1001
  - jupyter_client=6.1.2=py_0
  - jupyter_core=4.6.3=py38_0
  - kealib=1.4.13=hec59c27_0
  - kiwisolver=1.2.0=py38hbf85e49_0
  - krb5=1.16.4=h173b8e3_0
  - ld_impl_linux-64=2.34=h53a641e_0
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libclang=9.0.1=default_hde54327_0
  - libcurl=7.67.0=h20c2e04_0
  - libdap4=3.20.4=hd3bb157_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgdal=3.0.4=h94bbfbd_3
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libgomp=9.2.0=h24d8f2e_2
  - libiconv=1.15=h516909a_1006
  - libkml=1.3.0=hb574062_1011
  - liblapack=3.8.0=14_openblas
  - libllvm9=9.0.1=hc9558a2_0
  - libnetcdf=4.7.4=nompi_h9f9fd6a_101
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_1
  - libpq=12.2=hae5116b_0
  - libprotobuf=3.11.4=h8b12597_0
  - libsodium=1.0.16=h1bed415_0
  - libspatialindex=1.9.3=he6710b0_0
  - libspatialite=4.3.0a=heb269f5_1037
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - lz4-c=1.8.3=he1b5a44_1001
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1=py38h2af1d28_0
  - munch=2.5.0=py_0
  - ncurses=6.1=hf484d3e_1002
  - nspr=4.25=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.18.1=py38h8854b6b_1
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1f=h516909a_0
  - pandas=1.0.3=py38h0573a6f_0
  - parso=0.6.2=py_0
  - patsy=0.5.1=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pip=20.0.2=py_2
  - pixman=0.38.0=h516909a_1003
  - poppler=0.67.0=h14e79db_8
  - poppler-data=0.4.9=1
  - postgresql=12.2=hf1211e9_0
  - proj=6.3.1=hc80f0dc_1
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - protobuf=3.11.4=py38h950e882_1
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py38_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=2.6.0=py38h95a477d_0
  - pyqt=5.12.3=py38hcca6a23_1
  - pysocks=1.7.1=py38h32f6830_1
  - python=3.8.2=h8356626_5_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2019.3=py_0
  - pyzmq=18.1.1=py38he6710b0_0
  - qt=5.12.5=hd8c4c69_1
  - rasterio=1.1.3=py38h900e953_0
  - readline=8.0=hf8c457e_0
  - requests=2.23.0=pyh8c360ce_2
  - rsa=4.0=py_0
  - rtree=0.9.3=py38_0
  - scikit-learn=0.22.2.post1=py38hcdab131_0
  - scipy=1.4.1=py38h18bccfc_3
  - seaborn=0.10.0=py_1
  - setuptools=46.1.3=py38h32f6830_0
  - shapely=1.7.0=py38hd168ffb_3
  - simplejson=3.17.0=py38h516909a_0
  - six=1.14.0=py_1
  - snuggs=1.4.7=py_0
  - sqlite=3.31.1=h7b6447c_0
  - statsmodels=0.11.1=py38h1e0a361_1
  - tbb=2018.0.5=h2d50403_0
  - tiledb=1.7.0=hcde45ca_2
  - tk=8.6.10=hed695b0_0
  - tornado=6.0.4=py38h7b6447c_1
  - tqdm=4.44.1=py_0
  - traitlets=4.3.3=py38_0
  - tzcode=2019a=h516909a_1002
  - uritemplate=3.0.1=py_0
  - urllib3=1.25.7=py38h32f6830_1
  - wcwidth=0.1.9=py_0
  - wheel=0.34.2=py_1
  - xerces-c=3.2.2=h8412b87_1004
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h516909a_1002
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_2
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
prefix: /home/cholo/anaconda3/envs/ee

